name: SAITS-env

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - conda-forge::python >=3.8.8
  - conda-forge::numpy
  - conda-forge::matplotlib
  - conda-forge::scikit-learn
  - conda-forge::h5py
  - conda-forge::pandas
  - conda-forge::tensorboard
  - pytorch::pytorch >=1.8.1
  - pip:
    - nni==2.1