name: "Close stale issues and PRs"

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue had no activity for **14 days**. It will be closed in **1 week** unless there is some new activity. Is this issue already resolved?'
          stale-issue-label: 'stale'
          exempt-issue-labels: bug, enhancement, new feature, new model, good first issue, keep
          stale-pr-message: 'This pull request had no activity for **14 days**. It will be closed in **1 week** unless there is some new activity.'
          stale-pr-label: 'stale'
          days-before-stale: 14
          days-before-close: 7
          operations-per-run: 200
